### ISSUE TITLE
"cohensd_rm()" CIs inconsistent with ESCI

### ISSUE THREAD

**Issue by mattqh** [gitrman/itns#2]
This seems to be due to the fact that "n" is calculated as "length(x) - 1" rather than "length(x)"

My comparison is based on "ESCI Mac chapters 5-6 Jul 4 2011" on the "data paired" sheet. Downloaded from http://www.newstatistics.blogsite.org/itns/esci/esci-for-utns/

I hope this helps. Thanks for making this resource available!
-Matt

**Comment by gitrman** [comment]
You are correct @mattqh, `n` is being calculated incorrectly.  Thanks for picking this up.  I'll fix very shortly.

**Comment by mattqh** [comment]
Great! I've also noticed that this function seems to treat pre- and post-test opposite to ESCI, so to get the same result as ESCI I have to reverse my "x" and "y" arguments. A minor adjustment, but I thought you might want to be aware of it.

-Matt
